#!/bin/bash
# Generate src/books/YEAR/generated.journal from the CSV exports in
# src/input_data, using the import rules in src/books/rules/import.
#
# Pure: the output depends only on the CSVs and the rules, so running it twice
# gives the same file. Only transactions dated in YEAR are kept, so CSVs that
# span several years can be shared by several yearly books.
#
# Usage: src/scripts/build.sh YEAR

set -euo pipefail

year="${1:?usage: src/scripts/build.sh YEAR}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
input="$root/src/input_data"
rules="$root/src/books/rules/import"
out="$root/src/books/$year/generated.journal"

# One source per line: rules file | CSV glob (relative to src/input_data).
sources=(
    "bank_a__checking.rules|Bank A/CSV History/Checking/bank_a_checking_*.csv"
    "bank_a__savings_1.rules|Bank A/CSV History/Savings 1/bank_a_savings_1_*.csv"
    "swile__meal_vouchers.rules|Swile/swile-data-*.csv"
    "bank_b__checking.rules|Bank B/CSV History/Checking/bank_b_checking_*.csv"
    "bank_b__investment_securities.rules|Bank B/CSV History/Investment/bank_b_investment_securities_*.csv"
    "bank_b__investment_cash.rules|Bank B/CSV History/Investment/bank_b_investment_cash_*.csv"
    "broker_a__trades.rules|Broker A/Trade History/broker_a_trades_*.csv"
    "broker_b__trades.rules|Broker B/Trade History/broker-b-trades-*.csv"
    "broker_c__trades.rules|Broker C/Trade History/broker-c-trades-*.csv"
    "broker_c__ledgers.rules|Broker C/Ledgers/broker-c-ledgers-*.csv"
)

[ -d "$root/src/books/$year" ] || {
    echo "No book for $year (run: just new $year)" >&2
    exit 1
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    echo "; Generated by src/scripts/build.sh from the CSVs in src/input_data."
    echo "; Do not edit: fix the rules (src/books/rules) and rebuild."
    for source in "${sources[@]}"; do
        rules_file="${source%%|*}"
        pattern="${source#*|}"
        # Expand the glob without splitting paths on spaces
        shopt -s nullglob
        IFS=$'\n'
        # shellcheck disable=SC2206
        csvs=($input/$pattern)
        unset IFS
        shopt -u nullglob
        [ ${#csvs[@]} -gt 0 ] || continue
        # common.journal sets the amount styles (decimal point, symbol after)
        args=(-f "$root/src/books/common.journal")
        for csv in "${csvs[@]}"; do args+=(-f "csv:$csv"); done
        # Several exports of the same account must not cover the same days,
        # or their common transactions would be imported twice
        if [ ${#csvs[@]} -gt 1 ]; then
            ranges=""
            for csv in "${csvs[@]}"; do
                dates="$(hledger -f "csv:$csv" --rules "$rules/$rules_file" print -I -O csv | tail -n +2 | cut -d, -f2 | tr -d '"' | sort -u)"
                [ -n "$dates" ] || continue
                ranges+="$(head -1 <<<"$dates") $(tail -1 <<<"$dates") ${csv#"$input"/}"$'\n'
            done
            overlap="$(sort <<<"$ranges" | awk 'NF && prev_end >= $1 {print prev " / " $3} NF {prev_end = $2; prev = $3}')"
            [ -z "$overlap" ] || {
                echo "Overlapping exports for $rules_file: $overlap" >&2
                exit 1
            }
        fi
        txns="$(hledger "${args[@]}" --rules "$rules/$rules_file" print "date:$year")"
        [ -n "$txns" ] || continue
        echo
        echo "; ==== $rules_file"
        for csv in "${csvs[@]}"; do echo ";      ${csv#"$input"/}"; done
        echo
        echo "$txns"
    done
} >"$tmp"

mv "$tmp" "$out"
trap - EXIT
echo "Wrote ${out#"$root"/}"
